name: Primary wf 
on: [workflow_dispatch]

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  call-echo-wf:
    uses: ./.github/workflows/secundary.yaml
    with:
      environment: develop
    secrets: inherit